# Prefix key
set -g prefix C-t
unbind C-b
bind C-t send-prefix

# Enable mouse (scroll, resize panes)
set -g mouse on

#set -g set-clipboard on

# Use 256-color support
set -g default-terminal "screen-256color"

set -g status-left-length 50

# fix shortcut key problem in VIM
unbind -n C-Left
unbind -n C-Right
unbind -n C-Up
unbind -n C-Down
